export interface DeviceCategories {
  title: string;
  items: string[];
}

export const DEVICE_CATEGORIES: DeviceCategories[] = [
  {
    title: "Smartphones & Tablets",
    items: [
      "iPhone 15 / 14 / 13 / 12 / 11 / X / SE",
      "iPhone 16-Serie und neuere iOS-Modelle",
      "iPad, iPad Air, iPad Mini & iPad Pro",
      "iOS & iPadOS 13+ IPTV-Apps",
      "Samsung Galaxy S / Z Fold / Z Flip / Note",
      "Google Pixel Smartphones",
      "OnePlus, Xiaomi, Redmi, Poco, Oppo, Realme",
      "Motorola, Nokia, Nothing, Sony Xperia, ASUS ROG",
      "Huawei, Honor und HarmonyOS-Geräte über Player-Apps",
      "Android-Smartphones mit Android 7+",
      "Samsung Galaxy Tab",
      "Lenovo Tab, Xiaomi Pad, OnePlus Pad, Oppo Pad",
      "Huawei MatePad & Honor Pad",
      "Amazon Fire HD Tablets",
      "IPTV Smarters, GSE IPTV, XCIPTV, Televizo",
      "TiviMate Companion, OTT Navigator, IPTV Extreme",
    ],
  },
  {
    title: "Smart TV & Streaming",
    items: [
      "Samsung Smart TV / Tizen OS (2016+)",
      "Samsung Tizen 2.4, 3.0, 4.0, 5.0, 6.0, 7.0+",
      "LG Smart TV / WebOS 3.0, 4.0, 5.0, 6.0, 22, 23, 24+",
      "Sony Bravia Google TV & Android TV",
      "Sony Bravia 2015+ Android TV & 2021+ Google TV",
      "Philips Saphi, Android TV & Google TV",
      "Philips Ambilight TV, Android TV, Google TV",
      "Panasonic Smart TV / My Home Screen",
      "Panasonic Android TV, Fire TV und OLED-/LCD-Serie",
      "Hisense VIDAA & Google TV",
      "Hisense VIDAA U3, U4, U5, U6, U7+",
      "TCL Roku TV, Android TV & Google TV",
      "TCL C/P/S-Serie, Roku TV und Google TV",
      "Sharp Android TV, Google TV & Aquos",
      "Toshiba Smart TV, Fire TV und Android TV",
      "Grundig, JVC, Hitachi, Vestel, Telefunken Smart TV",
      "Nokia Smart TV, Xiaomi TV, Metz, Loewe, Blaupunkt",
      "Roku TV, Fire TV Edition & Android TV Edition",
      "Smart TV mit Browser oder M3U/IPTV-Anwendung",
      "Smart IPTV, IBO Player, SET IPTV, Net IPTV",
      "SS IPTV, DuplexPlay, Flix IPTV, SmartOne IPTV",
      "Hot IPTV, Smart STB, Bay IPTV, Room IPTV",
    ],
  },
  {
    title: "Computer & Laptops",
    items: [
      "Windows 11 / 10 PCs & Laptops",
      "Windows 8.1 und Windows 7 über VLC/Kodi, falls unterstützt",
      "Microsoft Surface Pro, Laptop & Studio",
      "macOS MacBook, iMac, Mac Mini & Mac Studio",
      "macOS Sonoma, Ventura, Monterey und unterstützte ältere Versionen",
      "Linux Ubuntu, Debian, Fedora, Mint",
      "Arch, Manjaro, Pop!_OS, OpenSUSE & Raspberry Pi OS",
      "Chromebook & ChromeOS",
      "All-in-One-PCs, Gaming-Laptops & Workstations",
      "Mini-PC, Intel NUC, Beelink, Geekom",
      "Raspberry Pi 3/4/5 mit Kodi, VLC oder Browser",
      "VLC, Kodi, MyIPTV Player, IPTV Smarters",
      "Webplayer über Chrome, Edge, Firefox, Safari",
    ],
  },
  {
    title: "Streaming-Geräte",
    items: [
      "Amazon Fire TV Stick (alle Versionen)",
      "Fire TV Stick Lite, 4K, 4K Max & Cube",
      "Google Chromecast 3, Chromecast Ultra",
      "Chromecast mit Google TV HD & 4K",
      "Apple TV 4K & HD",
      "Apple TV tvOS 13+ über kompatible IPTV-Apps",
      "Roku Express, Premiere, Ultra & Streaming Stick",
      "Roku TV und Roku-OS-Geräte mit M3U-/Browser-Optionen",
      "Xiaomi Mi Box & Stick",
      "Xiaomi TV Stick 4K, Mi Box S 2nd Gen",
      "Nokia Streaming Box",
      "Strong Leap, Homatics Box, Mecool, Ugoos",
      "Nvidia Shield TV & Shield TV Pro",
      "Nvidia Shield 2015, 2017, 2019 Tube & Pro",
      "Realme TV Stick, Dynalink, TiVo Stream 4K",
      "Onn Android TV Box, Walmart Google TV Box",
      "Android TV Box mit Android 7+",
      "Amlogic S905/S912/S922 Box mit IPTV-Player",
    ],
  },
  {
    title: "TV-Boxen",
    items: [
      "MAG 250, 254, 256, 322, 324, 420, 520",
      "MAG 524, 540, 544, 555 und Ministra-/Stalker-Portale",
      "Formuler Z7, Z8, Z10, Z11, Z Mini, GTV",
      "Formuler Z Alpha, Z Nano, Z10 Pro Max, Z11 Pro Max",
      "BuzzTV XRS, X5, Classic, Vidstick",
      "BuzzTV XR/XR4000/XR4500/X5 AI-Serie",
      "Dreambox DM One, DM Two, DM920",
      "VU+ Zero, Uno, Duo, Solo, Ultimo",
      "Zgemma H9, H11, i55, H7",
      "Amiko, Octagon, Edision, Gigablue",
      "Mutant, Axas, Qviart, Dinobot, Wetek",
      "Enigma2, XtreamTV, Stalker Portal, Ministra",
      "TVIP, Infomir, AuraHD, Openbox",
      "Android STB mit MyTVOnline, Stalker oder Xtream Codes",
    ],
  },
  {
    title: "Spielekonsolen",
    items: [
      "PlayStation 5 & PlayStation 4",
      "PlayStation 3 über DLNA/Browser, falls verfügbar",
      "Xbox Series X | S",
      "Xbox One & One S/X",
      "Xbox 360 über Mediaplayer",
      "Nintendo Switch über Browser oder Aufnahme",
      "Nintendo Wii U über Browser, falls verfügbar",
      "Steam Deck über Browser, VLC oder Kodi",
      "ROG Ally / Legion Go, tragbare Windows-Konsolen",
      "AYANEO, MSI Claw und andere tragbare Windows-Konsolen",
    ],
  },
  {
    title: "Mediaplayer",
    items: [
      "Kodi (auf jedem Gerät)",
      "VLC Media Player",
      "VLC unter Windows, macOS, Linux, Android und iOS",
      "Plex, Jellyfin & Emby",
      "Perfect Player & IPTV Smarters",
      "TiviMate, OTT Navigator, XCIPTV",
      "GSE Smart IPTV, IBO Player, Televizo",
      "ProgTV, Lazy IPTV, IPTV Extreme",
      "Smarters Pro, SmartOne IPTV, Net IPTV",
      "M3U-Playlist, Xtream-Codes-API, Stalker-Portal",
      "EPG XMLTV, Catch-up und Mehrfachbildschirm je nach App",
      "M3U8, HLS, TS-Streams & externer Player",
    ],
  },
  {
    title: "Browser",
    items: [
      "Google Chrome",
      "Chrome Desktop, Android & ChromeOS",
      "Safari",
      "Safari macOS & iOS/iPadOS",
      "Mozilla Firefox",
      "Microsoft Edge",
      "Opera & Brave",
      "Samsung Internet",
      "Android-WebView-Browser",
      "Silk-Browser auf Fire TV",
      "TV-Browser auf LG, Samsung, Philips und Sony",
      "Webplayer auf Computer, Tablet und Mobilgerät",
      "Chromium-Browser wie Vivaldi, Arc und Yandex",
      "Browser mit HLS-/M3U8-Unterstützung",
    ],
  },
];
